### ISSUE TITLE
Maybe a rooted environment?

### ISSUE THREAD

**Issue by lifehome** [adarkhorse/MobIVRS#1]
Just thinking of using Android phones as IVRS systems, and this repo pops up.

But kinda tricky when things are restricted due to the natural environment of Android, wondering if a rooted environment is easier for devs and the app itself to intercept the call audio stream?

**Comment by adarkhorse** [comment]
We have faced the same restrictions and for now, we have made a workaround which includes sending voice information using the speaker of the phone. This setting works but then the user cannot take his phone to a meeting or a place which requires silence. 

We are also trying to figure out other ways like rooted environment to get hold of the mic so that we can directly send the voice using mic and not use the speaker for that purpose.  

Maybe we can join forces and make a SOTA functional system for android. Let us know if you feel like joining.

Thanks and Regards
Nishant Sharma
